version: 2.1

jobs:
  test-routes:
    docker:
      - image: cimg/python:3.8.10
    environment:
      PYTHONPATH: . 
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          environment:
            COMPOSE_VERSION: '1.29.2'
          command: |
            curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose

      - run:
          name: "Test routes"
          command: |
            pip install -r requirements.txt
            docker-compose up -d
            python -m pytest -v --disable-warnings --durations=0

  # build-container:
  #   docker:
  #     - image: cimg/python:3.8.10
  #   environment:
  #     PROJECT_NAME: ml-api

  #   steps: 
  #     - checkout
  #     - setup_remote_docker
  #     - run:
  #         name: "Build docker image"
  #         command: |
  #           docker build -t $DOCKER_USERNAME/$PROJECT_NAME .
  #           echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
  #           docker push $DOCKER_USERNAME/$PROJECT_NAME:latest
workflows:
  main:
    jobs:
      - test-routes:
          filters:
            branches:
              only: 
                DEVELOPMENT
      # - build-container:
      #     requires:
      #       - test-models
      #     filters:
      #       branches:
      #         only: 
      #           master